package planfile

// Discovery: what plans can this project run, and what does each contain
// (roadmap L3.37)?
//
// `loom run --plan x` resolves one name. Choosing between plans needs the
// set, and composing a new one needs the stages available to put in it —
// neither of which the parse path exposes.

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/orieken/loom/internal/orchestrator"
)

// Available is one plan a project can run.
type Available struct {
	Name string
	// Path is empty for the built-in plan, which is Go rather than a file.
	Path        string
	Description string
	Stages      []string
	// Err is set when a plan file exists but does not parse. A broken plan
	// is listed with its error rather than omitted: a plan that has silently
	// vanished from the list is harder to debug than one that says why.
	Err error
}

// IsBuiltIn reports whether this plan is the compiled default.
func (a Available) IsBuiltIn() bool { return a.Path == "" }

// SearchPath is where plan files live, project-local first: a project's own
// plan overrides one the framework installed under the same name, which is
// the precedence every other .claude/ resource has.
func SearchPath() []string {
	return []string{
		filepath.Join(".claude", "plans"),
		filepath.Join("shared", "plans"),
	}
}

// Discover lists every plan this project can run, the built-in first and the
// rest by name. A directory that does not exist contributes nothing, which is
// the normal case for a project that installed no plans.
func Discover(roots []string) []Available {
	plans := []Available{builtIn()}
	seen := map[string]bool{orchestrator.DefaultDeliverFeaturePlanName: true}
	for _, root := range roots {
		for _, found := range discoverIn(root) {
			if seen[found.Name] {
				continue
			}
			seen[found.Name] = true
			plans = append(plans, found)
		}
	}
	sort.SliceStable(plans[1:], func(left, right int) bool {
		return plans[left+1].Name < plans[right+1].Name
	})
	return plans
}

func builtIn() Available {
	plan := orchestrator.DefaultDeliverFeaturePlan()
	return Available{
		Name:        plan.Name,
		Description: "The framework's full delivery pipeline, compiled in.",
		Stages:      stageNames(plan),
	}
}

func discoverIn(root string) []Available {
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil
	}
	var found []Available
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".yaml" {
			continue
		}
		found = append(found, describe(filepath.Join(root, entry.Name())))
	}
	return found
}

func describe(path string) Available {
	name := strings.TrimSuffix(filepath.Base(path), ".yaml")
	source, err := os.ReadFile(path)
	if err != nil {
		return Available{Name: name, Path: path, Err: err}
	}
	plan, err := Parse(source, path)
	if err != nil {
		return Available{Name: name, Path: path, Err: err}
	}
	return Available{Name: plan.Name, Path: path,
		Description: descriptionOf(source), Stages: stageNames(plan)}
}

// descriptionOf reads the definition's own description, which Parse discards
// because the executor has no use for it. A chooser does.
func descriptionOf(source []byte) string {
	var definition Definition
	if err := unmarshalDefinition(source, &definition); err != nil {
		return ""
	}
	return strings.TrimSpace(definition.Description)
}

func stageNames(plan orchestrator.Plan) []string {
	names := make([]string, 0, len(plan.Stages))
	for _, stage := range plan.Stages {
		names = append(names, stage.ID)
	}
	return names
}

// SelectableStages lists the catalogue a plan may draw from, in the order the
// built-in plan runs them. Order is the built-in's because a plan selects and
// orders, and canonical order is the only ordering a chooser can offer
// without inventing one.
func SelectableStages() []string {
	return stageNames(orchestrator.DefaultDeliverFeaturePlan())
}

// Render turns a chosen name and stage set into a plan file, so what a
// chooser writes is the same format a human would have written by hand.
func Render(name, description string, stages, loops []string) []byte {
	var out strings.Builder
	fmt.Fprintf(&out, "# Generated by `loom plan new`. Edit freely — this is the same\n"+
		"# format `loom run --plan %s` reads, and hand edits are expected.\n", name)
	fmt.Fprintf(&out, "version: %d\nname: %s\n", Version, name)
	if description != "" {
		fmt.Fprintf(&out, "\ndescription: >\n  %s\n", description)
	}
	out.WriteString("\nstages:\n")
	for _, stage := range stages {
		fmt.Fprintf(&out, "  - %s\n", stage)
	}
	if len(loops) > 0 {
		out.WriteString("\nloops:\n")
		for _, loop := range loops {
			fmt.Fprintf(&out, "  - %s\n", loop)
		}
	}
	return []byte(out.String())
}

// SelectableLoops lists the loops a plan may name.
func SelectableLoops() []string {
	loops := orchestrator.BuiltInLoops()
	names := make([]string, 0, len(loops))
	for id := range loops {
		names = append(names, id)
	}
	sort.Strings(names)
	return names
}
